export const ERROR_CODES = {
  INVALID_ARGUMENT: {
    code: 'INVALID_ARGUMENT',
    id: 1001,
    status: 400,
    message: '参数格式非法',
  },
  UNAUTHENTICATED: {
    code: 'UNAUTHENTICATED',
    id: 1002,
    status: 401,
    message: '未授权访问',
  },
  FORBIDDEN: {
    code: 'FORBIDDEN',
    id: 1003,
    status: 403,
    message: '权限不足',
  },
  PROJECT_NOT_FOUND: {
    code: 'PROJECT_NOT_FOUND',
    id: 1004,
    status: 404,
    message: '项目不存在',
  },
  USER_NOT_FOUND: {
    code: 'USER_NOT_FOUND',
    id: 1005,
    status: 404,
    message: '用户不存在或已软删除',
  },
  USER_DISABLED: {
    code: 'USER_DISABLED',
    id: 1006,
    status: 403,
    message: '用户账号已被禁用',
  },
  INVALID_CREDENTIALS: {
    code: 'INVALID_CREDENTIALS',
    id: 1007,
    status: 401,
    message: '用户名或密码错误',
  },
  TOKEN_EXPIRED: {
    code: 'TOKEN_EXPIRED',
    id: 1008,
    status: 401,
    message: 'access_token 已过期',
  },
  TOKEN_INVALID: {
    code: 'TOKEN_INVALID',
    id: 1009,
    status: 401,
    message: 'token 签名失效或已在黑名单',
  },
  MEMBER_ALREADY_EXISTS: {
    code: 'MEMBER_ALREADY_EXISTS',
    id: 1010,
    status: 409,
    message: '该用户已是项目成员',
  },
  MEMBER_NOT_FOUND: {
    code: 'MEMBER_NOT_FOUND',
    id: 1011,
    status: 404,
    message: '成员记录不存在',
  },
  LAST_ADMIN_LOCKED: {
    code: 'LAST_ADMIN_LOCKED',
    id: 1012,
    status: 409,
    message: '试图移除或降级项目最后一个 admin',
  },
  ROLE_INVALID: {
    code: 'ROLE_INVALID',
    id: 1013,
    status: 400,
    message: '角色值不在 9 种枚举内',
  },
  USERNAME_EXISTS: {
    code: 'USERNAME_EXISTS',
    id: 1014,
    status: 409,
    message: '用户名已被占用',
  },
  EMAIL_EXISTS: {
    code: 'EMAIL_EXISTS',
    id: 1015,
    status: 409,
    message: '邮箱已被占用',
  },
  PASSWORD_TOO_WEAK: {
    code: 'PASSWORD_TOO_WEAK',
    id: 1016,
    status: 400,
    message: '密码强度不足：至少 8 位且必须包含字母和数字',
  },
  ADMIN_IMMUTABLE: {
    code: 'ADMIN_IMMUTABLE',
    id: 1017,
    status: 403,
    message: '项目 admin 成员不可被修改或移除',
  },
  ROUTE_NOT_FOUND: {
    code: 'ROUTE_NOT_FOUND',
    id: 2001,
    status: 404,
    message: '路由未找到',
  },
  RESOURCE_EXHAUSTED: {
    code: 'RESOURCE_EXHAUSTED',
    id: 2003,
    status: 429,
    message: '请求频率超限',
  },
  QUEUE_FULL: {
    code: 'QUEUE_FULL',
    id: 2004,
    status: 503,
    message: '队列已满',
  },
  QUEUE_DEAD: {
    code: 'QUEUE_DEAD',
    id: 2005,
    status: 200,
    message: '异步任务重试耗尽进入死信队列',
  },
  TARGET_TIMEOUT: {
    code: 'TARGET_TIMEOUT',
    id: 3001,
    status: 504,
    message: '下游服务超时',
  },
  TARGET_CIRCUIT_BROKEN: {
    code: 'TARGET_CIRCUIT_BROKEN',
    id: 3002,
    status: 503,
    message: '下游服务熔断',
  },
  TARGET_SERVER_ERROR: {
    code: 'TARGET_SERVER_ERROR',
    id: 3004,
    status: 502,
    message: '下游服务错误',
  },
  // 业务数据存储专用错误码（对齐 SPEC-04 §6.5）
  BUSINESS_TABLE_NOT_FOUND: {
    code: 'BUSINESS_TABLE_NOT_FOUND',
    id: 4001,
    status: 404,
    message: '业务表不存在',
  },
  BUSINESS_TABLE_NAME_CONFLICT: {
    code: 'BUSINESS_TABLE_NAME_CONFLICT',
    id: 4002,
    status: 409,
    message: '业务表名冲突',
  },
  FIELD_TYPE_MISMATCH: {
    code: 'FIELD_TYPE_MISMATCH',
    id: 4003,
    status: 400,
    message: '字段类型不匹配',
  },
  PRIMARY_KEY_IMMUTABLE: {
    code: 'PRIMARY_KEY_IMMUTABLE',
    id: 4004,
    status: 400,
    message: '主键不可修改',
  },
  CACHE_TABLE_BACKUP_FORBIDDEN: {
    code: 'CACHE_TABLE_BACKUP_FORBIDDEN',
    id: 4005,
    status: 403,
    message: '缓存表不允许备份',
  },
  TTL_INVALID: {
    code: 'TTL_INVALID',
    id: 4006,
    status: 400,
    message: 'TTL 配置非法',
  },
  FILE_NOT_FOUND: {
    code: 'FILE_NOT_FOUND',
    id: 4007,
    status: 404,
    message: '文件不存在',
  },
  FILE_TOO_LARGE: {
    code: 'FILE_TOO_LARGE',
    id: 4008,
    status: 413,
    message: '文件超过单文件大小上限',
  },
  FILE_TYPE_FORBIDDEN: {
    code: 'FILE_TYPE_FORBIDDEN',
    id: 4009,
    status: 415,
    message: '文件类型不在允许列表内',
  },
  FILE_FIELD_TYPE_REQUIRED: {
    code: 'FILE_FIELD_TYPE_REQUIRED',
    id: 4010,
    status: 400,
    message: '未指定业务表 ID 或该表无 file 类型字段',
  },
  INTERNAL_ERROR: {
    code: 'INTERNAL_ERROR',
    id: 9999,
    status: 500,
    message: '服务端内部异常',
  },
};

export type ErrorCode = keyof typeof ERROR_CODES;
